### ISSUE TITLE
Allow users to select an avatar to use for themselves

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1001]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
This is so that you will see your own contact (avatar) when looking at reactions. We could also make the convo list look more like a "profile" if we really wanted to go that route. Just gives us personalization options.

* New config for storing the person's contact ID
* When the app opens/loads, fetch the contact and store it somewhere to reference
* Edit the reactions popup to put your avatar or initials as the icon for your reactions

**Comment by tneotia** [comment]
Unfortunately it looks like contacts_service can't get the user contact in the list, at least on Samsung phones. We could make a screen where the user inputs their info if they want though.

**Comment by zlshames** [comment]
> Unfortunately it looks like contacts_service can't get the user contact in the list, at least on Samsung phones. We could make a screen where the user inputs their info if they want though.

Wait, so the plugin doesn't work for choosing a contact via the picker? Isn't that one of it's main features or am I misremembering?

**Comment by tneotia** [comment]
As far as I can tell there isn't a contact picker functionality. Even if there was it probably wouldn't help because the user contact isn't stored as an actual contact it seems:

![Screenshot_20210705-095322_Contacts.png](https://user-images.githubusercontent.com/50850142/124482243-13533900-dd77-11eb-994e-adb80b4d2051.png)

I have my profile set in the phone but it doesn't show up in the contact list from the plugin.

**Comment by zlshames** [comment]
@tneotia so I was assuming it wouldn't use your account with Samsung/OnePlus/whoever. I was assuming the user would just add themselves as a contact into their phone (I have myself in my own contacts). Then you can use an intent to ACTION_PICK or something to use the default contacts app to select yourself. 

Maybe it's not possible via the plugin, but I can't imagine why we can't do it regularly using our own intent handlers

**Comment by tneotia** [comment]
Ah I see. Well if you're a contact yourself then I would assume our logic for grabbing contacts would also grab you? As long as the email/phone number in the contact matches the sender email/phone number right? So we wouldn't need a picker.

**Comment by zlshames** [comment]
> Ah I see. Well if you're a contact yourself then I would assume our logic for grabbing contacts would also grab you? As long as the email/phone number in the contact matches the sender email/phone number right? So we wouldn't need a picker.

I don't think so tbh. I think if the handle ID is null or 0, we automatically use You. We don't use any specific avatar

**Comment by tneotia** [comment]
still not really sure how useful this is because their "avatar" would only ever show in reaction popups

**Comment by zlshames** [comment]
> still not really sure how useful this is because their "avatar" would only ever show in reaction popups

Also notifications

**Comment by zlshames** [comment]
> We don't ever show isFromMe messages in notifications

I meant replies, but maybe that's not worth it

**Comment by tneotia** [comment]
done
