### ISSUE TITLE
Selectively enable read receipts

### ISSUE THREAD

**Issue by jakeump** [BlueBubblesApp/bluebubbles-app#1087]
Would like to selectively enable read receipts natively (option is available on ios). right now I have to either turn on read receipts for a specific contact through Teamviewer or my iPad.

Selective read receipts is exactly how it sounds: turn on read receipts for specified contacts only, and leave it disabled for everyone else.

**Comment by zlshames** [comment]
This shouldn't be too hard. Though, whoever does it will need to have Private API features available (for full testing). However, it can be completed without it available. They just will need others to help test. 

As far as fixing the issue goes, here are some things that need to be done. 

1. Add a column to the `chat` DB table (you'll need to add it to the SQL create table code, as well as create a DB upgrade item for it). Name it something like `auto_send_read_receipts`. By default, it should be false
2. In the chat model, add the field. Also add a toggle function
3. In the conversation details page, add a toggle to turn on/off the auto sending of read receipts
4. In the code where we send read receipts, check if the private API is enabled && manual mark as read is off && send read receipts is on. If all conditions are met, check the column you just added to the DB to see if it's true. If it is, send the receipt, otherwise, don't.
