### ISSUE TITLE
Apple News link previews show `Invalid SSL Certificate`

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1893]
[This](https://stocks.apple.com/A2VsyATIFSUOCP7zCL8YsXA) is the link in the screenshot below. ![Image](https://cdn.discordapp.com/attachments/746560644995612752/946130885554622514/tempFileForShare_20220223-144551.jpg)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-support`.

**Comment by CSab6482** [comment]
This is how the Apple News link compares to the link that goes directly to the article.
![Screenshot_20220223-155309](https://user-images.githubusercontent.com/53708281/155406866-a0c215be-eb06-47f8-86b3-8b36ce8ee388.jpg)
and this is how it looks in [imcore.react](https://github.com/open-imcore/imcore.react). The link that doesn't show a preview is because of [this bug](https://github.com/BlueBubblesApp/bluebubbles-server/issues/244).
![image](https://user-images.githubusercontent.com/53708281/155407623-81fc289b-6077-4e22-8884-5b5f177f370d.png)
Similar behavior occurs in [AirMessage](https://github.com/airmessage/airmessage-android/issues/26)

**Comment by tneotia** [comment]
This is intentional:

```dart
 on HandshakeException catch (ex) {
      meta.title = 'Invalid SSL Certificate';
      meta.description = ex.message;
    }
```

and definitely something on Apple's end. Nothing we can do here.
