### ISSUE TITLE
Make syncing async

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1925]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Since syncing always happens at the beginning, when we don't have anything in the database, here is how we should set it up.

1. Fetch all chats from the server
2. Build ObjectBox Chat objects for all the chats and insert them all in one call (async)
    - If this does not return the inserted chat objects, we should fetch them
3. Create a key/value map for the chat GUIDs to the Chat objects
4. For each chat, fetch the associated messages from the server
5. Build ObjectBox Message objects for the messages and insert them in one call (async)
    - If this does not return the inserted message objects, we should fetch them
6. Create a key/value map for the message GUIDs to the Message objects
    - Since we limit the sync amount to 50 per chat, this would only be 50 messages loaded in memory, nothing major
7. For each message with an associated message, fetch the associated message from the key/value map and toggle the `hasReactions` flag
    - If the associated message GUID doesn't exist, no biggie, don't do anything
8. Increment the setup progress

**Some Notes**

* We do not need to call the heavy Chat.save() function ever here. This is because we don't need to make any checks before saving because theoretically these will be brand new to the database.
* We also do not need to update the chat bloc here because we will update it when the sync is fully completed
* I have a feeling doing it this way will make syncing lightning fast.
