### ISSUE TITLE
Chats from branded SMS show empty display names

### ISSUE THREAD

**Issue by 13lievre** [BlueBubblesApp/bluebubbles-app#2109]
Chats from branded SMS show empty display names. 

Here's link for info about branded sms: https://www.smsapi.com/blog/sender-id-how-to-send-branded-sms-company-name/

**Comment by 13lievre** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/68971123/172576892-1e170163-49c3-46da-a835-fc0119dbbcfd.png">

**Comment by 13lievre** [comment]
Spoke to Joel about this in a discord chat. He just wanted me to post it here as well.

**Comment by zlshames** [comment]
@tneotia I actually un-excluded the `urn:` chats from the chat query endpoint. For the same reason I include the archived chats by default now. Might as well show them, so long as the client can handle them. So I'm guessing that's the reason.

Prior, we excluded them because they caused the sync to break. It was hard to reproduce because we didn't have any `urn` chats ourselves

**Comment by tneotia** [comment]
Added better support - we cant show the business name but it wont be empty anymore
