### ISSUE TITLE
UnifiedPush support

### ISSUE THREAD

**Issue by ThatOneCalculator** [BlueBubblesApp/bluebubbles-app#2274]
As this is supposed to be a (F)OSS/self-hosted solution, UnifiedPush support as an alternative to Firebase Cloud Messaging would be greatly appreciated

**Comment by zlshames** [comment]
Leaving this here for reference:

* NodeJS: https://aerogear.github.io/aerogear-unifiedpush-server/docs/server_sdk/nodesender#node-sender
* Android: https://aerogear.github.io/aerogear-unifiedpush-server/docs/clients/android-client

The only thing im worried about is compatibility with the Android side since we dynamically load in the credentials vs. how they show it in the samples. I think it's do-able, but might be tricky.

**Comment by ThatOneCalculator** [comment]
Since this is a Flutter app, why not use the Flutter SDK? https://unifiedpush.org/developers/flutter/

**Comment by karmanyaahm** [comment]
Aerogear UnifiedPush and UnifiedPush.org are different things. UnifiedPush.org is a FOSS, decentralized alternative to FCM, whereas Aerogear is just a gateway for multiple centralized push services.

**Comment by ThatOneCalculator** [comment]
Yep. I'm talking about the FOSS decentralized one.
