### ISSUE TITLE
After changing servers, existing chats cause "Error (500): Chat does not exist!" on message send.

### ISSUE THREAD

**Issue by femboyfin** [BlueBubblesApp/bluebubbles-app#2335]
After swapping from macOS 10.13 High Sierra to 13.2 Ventura (fresh install with OCLP), I've been getting "Error (500): Chat does not exist!" when trying to send a message in previous chats.
My assumption is that because my previous chats don't exist in the Messages app on the Mac Mini running my BlueBubbles Server, the Android client is assuming the chats still exist on the server and trying to send a message in them with no fallback.

Either checking if a chat exists before sending a message or adding a user prompt/automatically creating a new chat when the client runs into a chat that doesn't exist on the server's side both seem like reasonable solutions (although admittedly I haven't looked at the inner workings of the project at all so I might be completely off-base).

**Comment by tneotia** [comment]
Technically we require that you fully reset and resync your android app when switching servers. There's a decent chance that not doing so causes contacts and messages to become out of order and not matched properly. That's why we don't really have great handling for a chat not existing, as its a case that shouldn't come up often.
