### ISSUE TITLE
Change github release package id to not conflict with Google Play

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-app#2704]
Because the Github release and Google Play release use the same package id, Google Play will attempt to update the Github release and fail.  Also, it's irritating to have Google shame you every time you go to update your apps that you disabled Auto update.  As long as Google doesn't allow you to hide apps from Google Play, a good remedy would be to use different package ids for the different builds.  This is a low priority issue, but I want it to be documented.

**Comment by tneotia** [comment]
We can't change this because of how they are signed. It would require everyone from GitHub to uninstall and reinstall the app, which is not ideal. Also, it allows Google Play to override GitHub builds which are not fully identical to the Play Store right now due to AA, so some people want to keep GitHub instead.

**Comment by tneotia** [comment]
It would, but anyone trying to update from old Github to new Github still needs to uninstall and reinstall, which is a highly breaking change

**Comment by SpaceSaver** [comment]
> It would, but anyone trying to update from old Github to new Github still needs to uninstall and reinstall, which is a highly breaking change

To be addressed later™️, ig lol
