### ISSUE TITLE
Partially (unintentionally) supports sending SMS relay. 

### ISSUE THREAD

**Issue by AidanLovelace** [BlueBubblesApp/bluebubbles-app#707]
My guess is that the Android app is not saving received SMS messages to it's database in the following cases:
 - Initial chat sync from the server
 - Message received from server as event

However, when a message is received as an event, the app will send a notification and add the chat to the conversation list with just that single. Note, the chat and message still are not stored in the database. So if the list is reloaded for some reason, like opening and closing the app, the conversation disappears.

There is one exception, you can force the app to store the SMS chat and messages in the database if, when it's in memory, you go to the conversation details and hit "Fetch more messages."

**Comment by zlshames** [comment]
Within the android app, we do not "ask" for SMS _things_, so that's why it doesn't seem to show up in the chat list. For instance, when we request the list of chats you have, we limit it to where `service = iMessage`. I guess it was an oversight for the `Fetch more messages` button, where I didn't include that service parameter. Hence, why you'll be able to fetch SMS from it. Kinda a but, kinda a feature, haha.

Either way, an easy fix would be to remove the `service = iMessage` specifier from all the requests to the server. The reason I left it out originally was because we had no time/dev effort to add SMS, so we purposefully excluded it. There also isn't a sure-fire way to send SMS via android. You can send via the AppleScript, but it won't always work.

We want a native SMS integration for the Android App, ultimately. One that actually hooks into the SMS API, rather than going through iMessage. I'm labelling this as both an enhancement and a bug because it kinda sits in the middle.
