### ISSUE TITLE
When sending text with a link, the text sends after the link

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#796]
The text should be sent before the link

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by zlshames** [comment]
This could be due to _not_ using a queue system for sending. Should probably build a queue system for sending those messages in the correct order.

Cole says the following: `So if I was to send "search for dogs" after sending the message containing the link, it will try to send until "go to" and not the embedded "youtube.com" link. And then when it finally sends it will go below the embedded "youtube.com" link`

**Comment by tneotia** [comment]
shouldn't be an issue anymore with message queing and link splitting
