### ISSUE TITLE
Improve Reliability of Attachment Downloader

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#817]
Might be related to issue #713

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
Below is the video as well as a screenshot of the mirrored glitch

https://user-images.githubusercontent.com/53708281/112392599-0f237400-8cd0-11eb-94c8-0c54f7ddf7d1.mp4

![Screenshot_20210324-181415_Gallery](https://user-images.githubusercontent.com/53708281/112392609-12b6fb00-8cd0-11eb-83f9-27940472aa2c.jpeg)

**Comment by zlshames** [comment]
To elaborate a little. I think the issue is that the full bytes are not fetched, but the metadata specifies a size. So the renderer might just repeat the last 'x' bytes if it sees some are missing based on the save. Not sure. That may be 100% wrong.

In any case, we need to use hashes for the temp GUIDs and have checks to see if the attachment download has started, finished, or never happened. Then complete a workflow to download the data

**Comment by zlshames** [comment]
Leaving this open for now
