### ISSUE TITLE
[GetX Migration] Migrate page navigation

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#943]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by tneotia** [comment]
We should use named routes and pass data via parameters or arguments when navigating (or create a shared Getx controller for the data if it's too cumbersome for those methods).

**Comment by zlshames** [comment]
> We should use named routes and pass data via parameters or arguments when navigating (or create a shared Getx controller for the data if it's too cumbersome for those methods).

Don't we kinda already do this without GetX? What's the benefit of using GetX here?

**Comment by tneotia** [comment]
Named routes are cleaner and you can do stuff like `Get.toNamed('/route?chat_title="test"')` and grab "test" in the page associated with /route. Just makes it easier to send data back and forth rather than creating a class instance for the page with the data imho. But our current way is fine.

Even if we don't want to transition fully to GetX navigation I would recommend switching to contextless navigation to make it a lot easier.

**Comment by tneotia** [comment]
This is complete with the tablet mode navigation, we use GetX to push pages to the stack
