### ISSUE TITLE
Toggle to not group notifications so badges are accurate to new message count

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#953]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
So, this is because of the way Samsung (specifically -- doesn't occur on OxygenOS) does notifications. Let's say you are at your homescreen (with BlueBubbles on it). And you get a notification from friend X. You'll get a `1` badge on BlueBubbles. Now, let's say the same person sends you another text. Well, the notification shows up, however, the badge stays at `1`. We need a toggle of some sort to make it so the badge will increment to 2.

Not 100% sure if this is possible from the app-side. Like I said, it's Samsung-specific, so it's a weird one.

**Comment by zlshames** [comment]
I'm closing this. I think we just take a stance on it and don't make it a toggle. My stance is that notification badges should be grouped by chat, just like the notifications. And in the app, the badge should match the number of unread chats, not texts
