### ISSUE TITLE
when starting a brand new chat, the message sends, but doesn't populate in the message view

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#965]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
You can leave and re-enter the chats to re-populate with new messages. However, the initial creation message won't show at first, which is the bug.

**Comment by tneotia** [comment]
Seems related to #939

**Comment by zlshames** [comment]
> Seems related to #939

i don’t think they are related. This one is more about refreshing the messages so that the message populates in the view, or pass it as a pre-loaded message. I think the other one is more of a matter of tracking the correct message to be marked as delivered or read, while also reacting to those new messages

**Comment by tneotia** [comment]
Resolved in rewrite
